from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from gate2_local_dither import local_edge_pairs, make_schedule, transfer_local_material
from self_carving import make_grid, node, operator_matrix


OMEGA = 1.35
PORT_OFFSETS = (-2, 0, 2)
TEACHER_SEED = 123
TEACHER_STEPS = 1000
EXTERNAL_TARGET_SEED = 4242
TRAIN_PROBES = 3
HELDOUT_PROBES = 64
SUCCESS_MATRIX_ERROR = 0.05
SUCCESS_HELDOUT_ERROR = 0.05
EVERY_SEED_MATRIX_ERROR = 0.10
RANDOM_CONTROL_FACTOR = 0.25


def matrix_ports(grid):
    """Three left input ports and three right output ports.

    These ports define a genuine 3x3 transfer matrix C H_g(omega) B while the
    material g is frozen. Inputs and outputs are distinct, so reciprocity of the
    full Green operator does not force this submatrix to be symmetric.
    """
    mid = grid.n // 2
    inputs = [node(grid.n, mid + dr, 1) for dr in PORT_OFFSETS]
    outputs = [node(grid.n, mid + dr, grid.n - 2) for dr in PORT_OFFSETS]
    return inputs, outputs


def solve_probe_block(grid, g: np.ndarray, x: np.ndarray, omega: float = OMEGA) -> np.ndarray:
    """Drive arbitrary dense input vectors and return output-port responses.

    x has shape (n_input_ports, n_probes). A whole probe is injected at once;
    no basis-vector query is needed during training.
    """
    inputs, outputs = matrix_ports(grid)
    if x.ndim != 2 or x.shape[0] != len(inputs):
        raise ValueError("x must have shape (3, n_probes)")
    rhs = np.zeros((grid.n * grid.n, x.shape[1]), dtype=complex)
    for k, source in enumerate(inputs):
        rhs[source, :] = x[k, :]
    u = np.linalg.solve(operator_matrix(grid, g, omega=omega), rhs)
    return u[outputs, :]


def effective_matrix(grid, g: np.ndarray, omega: float = OMEGA) -> np.ndarray:
    """Audit-only basis readback of the exposed 3x3 transfer operator."""
    return solve_probe_block(grid, g, np.eye(3, dtype=complex), omega=omega)


def dense_probes(count: int, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    x = rng.normal(size=(3, count)) + 1j * rng.normal(size=(3, count))
    x /= np.linalg.norm(x, axis=0, keepdims=True)
    return x


def hidden_teacher_material(grid, steps: int = TEACHER_STEPS, seed: int = TEACHER_SEED) -> np.ndarray:
    """Construct a hidden but physically reachable material state.

    This is deliberately a positive control for operator storage, not an
    arbitrary-matrix claim. It uses only conservative local transfers.
    """
    g = np.ones(len(grid.edges), dtype=float)
    pairs = local_edge_pairs(grid)
    rng = np.random.default_rng(seed)
    for _ in range(steps):
        ea, eb = map(int, pairs[int(rng.integers(len(pairs)))])
        cand = transfer_local_material(g, ea, eb, int(rng.integers(2)), delta=0.055)
        if cand is not None:
            g = cand
    return g


def external_dense_target(grid, seed: int = EXTERNAL_TARGET_SEED) -> np.ndarray:
    """A dense complex target not generated by any known lattice material."""
    blank = effective_matrix(grid, np.ones(len(grid.edges), dtype=float))
    rng = np.random.default_rng(seed)
    target = rng.normal(size=(3, 3)) + 1j * rng.normal(size=(3, 3))
    target *= np.linalg.norm(blank) / max(np.linalg.norm(target), 1e-30)
    return target


def target_definition(grid, kind: str):
    if kind == "reachable_teacher":
        teacher_g = hidden_teacher_material(grid)
        # The learner never receives this matrix. It receives only random
        # input/output examples generated by the hidden material.
        target_matrix = effective_matrix(grid, teacher_g)
        return target_matrix, teacher_g
    if kind == "external_random":
        return external_dense_target(grid), None
    raise ValueError(kind)


def normalized_probe_loss(grid, g: np.ndarray, x: np.ndarray, y_target: np.ndarray) -> float:
    y = solve_probe_block(grid, g, x)
    return float(np.linalg.norm(y - y_target) ** 2 / max(np.linalg.norm(y_target) ** 2, 1e-30))


def matrix_error(m: np.ndarray, target: np.ndarray) -> float:
    return float(np.linalg.norm(m - target) / max(np.linalg.norm(target), 1e-30))


def train_one(
    kind: str,
    mode: str,
    seed: int,
    n: int = 11,
    attempts: int = 1600,
    delta: float = 0.055,
    train_probes: int = TRAIN_PROBES,
):
    if mode not in {"consequence", "random_accept", "no_write"}:
        raise ValueError(mode)
    grid = make_grid(n)
    g = np.ones(len(grid.edges), dtype=float)
    total0 = float(np.sum(g))
    target_matrix, teacher_g = target_definition(grid, kind)

    # Training probes are dense random vectors. Basis vectors are reserved for
    # the audit after all structural learning has stopped.
    x_train = dense_probes(train_probes, 10000 + seed)
    y_train = target_matrix @ x_train
    train_rank = int(np.linalg.matrix_rank(x_train))
    min_component = float(np.min(np.abs(x_train)))

    x_heldout = dense_probes(HELDOUT_PROBES, 20000 + seed)
    y_heldout = target_matrix @ x_heldout

    blank_matrix = effective_matrix(grid, g)
    blank_matrix_error = matrix_error(blank_matrix, target_matrix)
    blank_heldout_error = float(
        np.linalg.norm(blank_matrix @ x_heldout - y_heldout)
        / max(np.linalg.norm(y_heldout), 1e-30)
    )

    current_loss = normalized_probe_loss(grid, g, x_train, y_train)
    initial_loss = current_loss
    accepted = 0
    proposed = 0
    pairs = local_edge_pairs(grid)
    schedule = make_schedule(len(pairs), attempts, seed)
    checkpoints = {1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 800, 1200, attempts}
    trajectory = [{"attempt": 0, "train_loss": current_loss}]

    if mode != "no_write":
        for k in range(attempts):
            ea, eb = map(int, pairs[int(schedule.pair_index[k])])
            cand = transfer_local_material(g, ea, eb, int(schedule.orientation[k]), delta=delta)
            if cand is None:
                continue
            proposed += 1
            candidate_loss = normalized_probe_loss(grid, cand, x_train, y_train)
            if mode == "consequence":
                take = candidate_loss < current_loss - 1e-14
            else:
                take = bool(schedule.coin[k] < 0.5)
            if take:
                g = cand
                current_loss = candidate_loss
                accepted += 1
            if (k + 1) in checkpoints:
                trajectory.append({"attempt": k + 1, "train_loss": current_loss})

    # All fast wave state is absent here: every solve above is steady-state and
    # independent. Only g persists. Now we ask basis questions that were never
    # used for training and reconstruct the matrix column by column.
    recovered = effective_matrix(grid, g)
    recovered_matrix_error = matrix_error(recovered, target_matrix)
    heldout_error = float(
        np.linalg.norm(recovered @ x_heldout - y_heldout)
        / max(np.linalg.norm(y_heldout), 1e-30)
    )

    result = {
        "kind": kind,
        "mode": mode,
        "seed": seed,
        "n": n,
        "omega": OMEGA,
        "attempts": attempts,
        "delta": delta,
        "train_probe_count": train_probes,
        "train_probe_rank": train_rank,
        "train_probe_min_component_abs": min_component,
        "basis_vectors_used_during_training": False,
        "teacher_material_hidden_from_learner": kind == "reachable_teacher",
        "initial_train_loss": initial_loss,
        "final_train_loss": current_loss,
        "blank_matrix_error": blank_matrix_error,
        "recovered_matrix_error": recovered_matrix_error,
        "blank_heldout_error": blank_heldout_error,
        "heldout_error": heldout_error,
        "accepted": accepted,
        "proposed": proposed,
        "acceptance_fraction": accepted / max(proposed, 1),
        "changed_edges": int(np.count_nonzero(np.abs(g - 1.0) > 1e-12)),
        "material_sum_relative_error": abs(float(np.sum(g)) - total0) / total0,
        "target_matrix": complex_matrix_json(target_matrix),
        "recovered_matrix": complex_matrix_json(recovered),
        "blank_matrix": complex_matrix_json(blank_matrix),
        "trajectory": trajectory,
    }
    if teacher_g is not None:
        result["teacher_material_sum_relative_error"] = abs(float(np.sum(teacher_g)) - total0) / total0
        result["teacher_changed_edges"] = int(np.count_nonzero(np.abs(teacher_g - 1.0) > 1e-12))
    return {"grid": grid, "g": g, "result": result}


def complex_matrix_json(m: np.ndarray):
    return [
        [{"re": float(z.real), "im": float(z.imag)} for z in row]
        for row in np.asarray(m)
    ]


def summarize(runs):
    rows = [x["result"] for x in runs]
    arr = lambda key: np.asarray([float(r[key]) for r in rows])
    return {
        "seeds": [int(r["seed"]) for r in rows],
        "median_blank_matrix_error": float(np.median(arr("blank_matrix_error"))),
        "median_recovered_matrix_error": float(np.median(arr("recovered_matrix_error"))),
        "max_recovered_matrix_error": float(np.max(arr("recovered_matrix_error"))),
        "median_blank_heldout_error": float(np.median(arr("blank_heldout_error"))),
        "median_heldout_error": float(np.median(arr("heldout_error"))),
        "median_final_train_loss": float(np.median(arr("final_train_loss"))),
        "median_acceptance_fraction": float(np.median(arr("acceptance_fraction"))),
        "max_material_sum_relative_error": float(np.max(arr("material_sum_relative_error"))),
    }


def run_all(out_dir: Path, seeds: int = 3, attempts: int = 1600):
    out_dir.mkdir(parents=True, exist_ok=True)
    kinds = ("reachable_teacher", "external_random")
    modes = ("consequence", "random_accept", "no_write")
    runs = {
        kind: {
            mode: [train_one(kind, mode, seed=s, attempts=attempts) for s in range(seeds)]
            for mode in modes
        }
        for kind in kinds
    }
    summary = {
        kind: {mode: summarize(runs[kind][mode]) for mode in modes}
        for kind in kinds
    }

    pos = summary["reachable_teacher"]["consequence"]
    rnd = summary["reachable_teacher"]["random_accept"]
    reachable_success = bool(
        pos["median_recovered_matrix_error"] <= SUCCESS_MATRIX_ERROR
        and pos["median_heldout_error"] <= SUCCESS_HELDOUT_ERROR
        and pos["max_recovered_matrix_error"] <= EVERY_SEED_MATRIX_ERROR
        and pos["median_recovered_matrix_error"]
        <= RANDOM_CONTROL_FACTOR * max(rnd["median_recovered_matrix_error"], 1e-30)
    )

    ext = summary["external_random"]["consequence"]
    external_arbitrary_success = bool(
        ext["median_recovered_matrix_error"] <= SUCCESS_MATRIX_ERROR
        and ext["max_recovered_matrix_error"] <= EVERY_SEED_MATRIX_ERROR
    )

    if reachable_success and external_arbitrary_success:
        verdict = "dense_operator_readback_and_external_target_both_succeed"
    elif reachable_success:
        verdict = "physically_reachable_operator_readback_succeeds_but_arbitrary_matrix_claim_fails"
    else:
        verdict = "dense_operator_readback_not_established"

    receipt = {
        "gate": 10,
        "question": "Can conserved local material encode a dense linear transfer operator learned only from dense random probes, and can that operator be read back later with basis queries?",
        "operator": "M_g = C [K(g)-omega^2 I + i omega Gamma]^{-1} B",
        "positive_control": "A hidden material state defines a physically reachable dense complex 3x3 teacher operator. Student material begins blank and sees only three dense random input/output probe pairs, never basis vectors or teacher g.",
        "attack": "Repeat the identical learner against an unrelated dense complex 3x3 target normalized to the blank operator norm; this target is not generated from any known material state.",
        "readback": "After learning stops, basis vectors e1,e2,e3 reconstruct the three columns of M_hat. These basis probes never enter acceptance decisions.",
        "success_thresholds_fixed_in_code_before_ci_receipt": {
            "median_reachable_matrix_error_at_most": SUCCESS_MATRIX_ERROR,
            "median_reachable_heldout_error_at_most": SUCCESS_HELDOUT_ERROR,
            "every_seed_reachable_matrix_error_at_most": EVERY_SEED_MATRIX_ERROR,
            "reachable_median_error_at_most_random_control_times": RANDOM_CONTROL_FACTOR,
        },
        "summary": summary,
        "reachable_success": reachable_success,
        "external_arbitrary_success": external_arbitrary_success,
        "verdict": verdict,
        "runs": {
            kind: {mode: [x["result"] for x in rs] for mode, rs in by_mode.items()}
            for kind, by_mode in runs.items()
        },
        "claim_boundary": "A positive reachable-teacher result establishes system identification/storage of an operator already realizable by this lattice family. It does not establish that arbitrary matrices are realizable, that this is more efficient than digital matrix storage, or that the mechanism is biological.",
    }
    (out_dir / "gate10_dense_operator_readback.json").write_text(
        json.dumps(receipt, indent=2), encoding="utf-8"
    )
    return receipt


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="results")
    p.add_argument("--seeds", type=int, default=3)
    p.add_argument("--attempts", type=int, default=1600)
    args = p.parse_args()
    receipt = run_all(Path(args.out), seeds=args.seeds, attempts=args.attempts)
    print(json.dumps({"summary": receipt["summary"], "verdict": receipt["verdict"]}, indent=2))


if __name__ == "__main__":
    main()
