from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from gate2_local_dither import local_edge_pairs, transfer_local_material
from gate6_learned_addressing import (
    Address,
    baseline_floor,
    choice_records,
    exact_matrix,
    family_measure,
    init_selector,
    oracle_choices,
    selector_choices,
    task_measure,
    task_port_indices,
)
from self_carving import make_grid, write_svg


def stress_addresses() -> list[Address]:
    """A denser address bank than Gate 6A so nearby alternatives can exchange rank."""
    return [
        Address(source_dr=dr, omega=omega)
        for dr in (-1, 0, 1)
        for omega in (1.30, 1.425, 1.55, 1.675, 1.80)
    ]


def run_mode(
    mode: str,
    seed: int,
    n: int = 11,
    epochs: int = 45,
    slow_proposals: int = 36,
    probes_per_task: int = 6,
    delta: float = 0.055,
    floor_fraction: float = 0.01,
    epsilon: float = 0.40,
    ema: float = 0.45,
):
    """Stress the address selector with interference generated by learning itself.

    Only one task is structurally trained in each epoch. Its accepted local material
    transfers are allowed to hurt the two inactive tasks. Because all tasks share g,
    their best (source, frequency) addresses can move even though their task labels
    and receivers do not. `coadaptive` must track those moves from scalar probes.

    `oracle_fast` is an audit upper bound that is explicitly given the full address
    scan before each structural block. It is not the claimed learning mechanism.
    """
    allowed = {"coadaptive", "stale", "oracle_fast", "selector_only"}
    if mode not in allowed:
        raise ValueError(mode)

    grid = make_grid(n)
    addr = stress_addresses()
    tasks = task_port_indices(grid)
    g = np.ones(len(grid.edges), dtype=float)
    total0 = float(np.sum(g))
    sigma2 = baseline_floor(grid, tasks, addr, floor_fraction)

    baseline_matrix = exact_matrix(grid, g, tasks, addr, sigma2)
    values, _counts = init_selector(baseline_matrix)
    initial_oracle = oracle_choices(baseline_matrix)
    frozen_choices = initial_oracle.copy()
    last_oracle = initial_oracle.copy()
    last_selected = initial_oracle.copy()

    # Structural proposal stream is independent of selector sampling and identical
    # across modes for a given seed.
    pairs = local_edge_pairs(grid)
    total_proposals = epochs * slow_proposals
    structure_rng = np.random.default_rng(10000 + seed)
    pair_schedule = structure_rng.integers(len(pairs), size=total_proposals)
    orientation_schedule = np.where(
        structure_rng.random(total_proposals) < 0.5, 1, -1
    ).astype(int)
    selector_rng = np.random.default_rng(20000 + seed)

    accepted = 0
    proposed = 0
    oracle_switches = 0
    selector_switches = 0
    inactive_damage_epochs = 0
    inactive_improve_epochs = 0
    trajectory = []

    def probe_selector() -> None:
        nonlocal selector_switches, last_selected
        if mode not in {"coadaptive", "selector_only"}:
            return
        for q, ti in enumerate(tasks):
            for _ in range(probes_per_task):
                if selector_rng.random() < epsilon:
                    ai = int(selector_rng.integers(len(addr)))
                else:
                    ai = int(np.argmax(values[q]))
                m = task_measure(grid, g, ti, addr[ai], sigma2)
                values[q, ai] = (
                    (1.0 - ema) * values[q, ai] + ema * float(m["utility"])
                )
        now = selector_choices(values)
        selector_switches += int(np.count_nonzero(now != last_selected))
        last_selected = now.copy()

    schedule_cursor = 0
    for epoch in range(epochs):
        probe_selector()
        active_q = epoch % len(tasks)

        if mode == "stale":
            choices = frozen_choices.copy()
        elif mode == "oracle_fast":
            choices = oracle_choices(exact_matrix(grid, g, tasks, addr, sigma2))
        else:
            choices = selector_choices(values)

        before_audit = exact_matrix(grid, g, tasks, addr, sigma2)
        before_oracle = oracle_choices(before_audit)
        before_oracle_eval = family_measure(
            grid, g, tasks, addr, before_oracle, sigma2
        )
        before_best_util = np.asarray(
            [max(float(m["utility"]) for m in row) for row in before_audit]
        )

        if mode != "selector_only":
            ti = tasks[active_q]
            ai = int(choices[active_q])
            current = task_measure(grid, g, ti, addr[ai], sigma2)
            for _ in range(slow_proposals):
                pi = int(pair_schedule[schedule_cursor])
                orientation = int(orientation_schedule[schedule_cursor])
                schedule_cursor += 1
                ea, eb = map(int, pairs[pi])
                cand = transfer_local_material(g, ea, eb, orientation, delta=delta)
                if cand is None:
                    continue
                proposed += 1
                cm = task_measure(grid, cand, ti, addr[ai], sigma2)
                if float(cm["utility"]) > float(current["utility"]) + 1e-14:
                    g = cand
                    current = cm
                    accepted += 1
        else:
            schedule_cursor += slow_proposals

        after_audit = exact_matrix(grid, g, tasks, addr, sigma2)
        after_oracle = oracle_choices(after_audit)
        after_best_util = np.asarray(
            [max(float(m["utility"]) for m in row) for row in after_audit]
        )
        oracle_switches += int(np.count_nonzero(after_oracle != last_oracle))
        last_oracle = after_oracle.copy()

        inactive = [q for q in range(len(tasks)) if q != active_q]
        if any(after_best_util[q] < before_best_util[q] - 1e-10 for q in inactive):
            inactive_damage_epochs += 1
        if any(after_best_util[q] > before_best_util[q] + 1e-10 for q in inactive):
            inactive_improve_epochs += 1

        if mode == "stale":
            report_choices = frozen_choices.copy()
        elif mode == "oracle_fast":
            report_choices = after_oracle.copy()
        else:
            # Probe again after the structural block so the online selector gets a
            # chance to react to the environment it just helped change.
            probe_selector()
            report_choices = selector_choices(values)

        selected_eval = family_measure(
            grid, g, tasks, addr, report_choices, sigma2
        )
        oracle_eval = family_measure(grid, g, tasks, addr, after_oracle, sigma2)
        trajectory.append(
            {
                "epoch": epoch + 1,
                "active_task": int(active_q),
                "selected_choices": choice_records(addr, report_choices),
                "oracle_choices": choice_records(addr, after_oracle),
                "selected_min_ratio": float(selected_eval["min_ratio"]),
                "selected_rank1_fraction": float(selected_eval["rank1_fraction"]),
                "oracle_min_ratio": float(oracle_eval["min_ratio"]),
                "oracle_rank1_fraction": float(oracle_eval["rank1_fraction"]),
                "oracle_min_ratio_before_block": float(before_oracle_eval["min_ratio"]),
            }
        )

    final_matrix = exact_matrix(grid, g, tasks, addr, sigma2)
    final_oracle = oracle_choices(final_matrix)
    if mode == "stale":
        final_selected = frozen_choices.copy()
    elif mode == "oracle_fast":
        final_selected = final_oracle.copy()
    else:
        final_selected = selector_choices(values)

    baseline_oracle_eval = family_measure(
        grid, np.ones_like(g), tasks, addr, initial_oracle, sigma2
    )
    final_selected_eval = family_measure(
        grid, g, tasks, addr, final_selected, sigma2
    )
    final_oracle_eval = family_measure(
        grid, g, tasks, addr, final_oracle, sigma2
    )

    result = {
        "mode": mode,
        "seed": seed,
        "epochs": epochs,
        "slow_proposals_per_epoch": slow_proposals,
        "addresses": [a.__dict__ for a in addr],
        "task_port_indices": [int(x) for x in tasks],
        "accepted": accepted,
        "proposed": proposed,
        "acceptance_fraction": accepted / max(proposed, 1),
        "material_sum_relative_error": abs(float(np.sum(g)) - total0) / total0,
        "changed_edges": int(np.count_nonzero(np.abs(g - 1.0) > 1e-12)),
        "oracle_address_switches": int(oracle_switches),
        "selector_switches": int(selector_switches),
        "inactive_damage_epochs": int(inactive_damage_epochs),
        "inactive_improve_epochs": int(inactive_improve_epochs),
        "initial_oracle_choices": choice_records(addr, initial_oracle),
        "final_selected_choices": choice_records(addr, final_selected),
        "final_oracle_choices": choice_records(addr, final_oracle),
        "selector_oracle_exact_fraction": float(np.mean(final_selected == final_oracle)),
        "distinct_final_selected_addresses": int(len(set(map(int, final_selected)))),
        "baseline_oracle": baseline_oracle_eval,
        "final_selected": final_selected_eval,
        "final_oracle": final_oracle_eval,
        "trajectory": trajectory,
    }
    return {"grid": grid, "g": g, "result": result}


def summarize(runs):
    rows = [x["result"] for x in runs]

    def vals(section, key):
        return np.asarray([float(r[section][key]) for r in rows])

    return {
        "seeds": [int(r["seed"]) for r in rows],
        "median_baseline_oracle_min_ratio": float(np.median(vals("baseline_oracle", "min_ratio"))),
        "median_final_selected_min_ratio": float(np.median(vals("final_selected", "min_ratio"))),
        "min_final_selected_min_ratio": float(np.min(vals("final_selected", "min_ratio"))),
        "median_final_selected_rank1_fraction": float(np.median(vals("final_selected", "rank1_fraction"))),
        "median_final_oracle_min_ratio": float(np.median(vals("final_oracle", "min_ratio"))),
        "median_final_oracle_rank1_fraction": float(np.median(vals("final_oracle", "rank1_fraction"))),
        "median_selector_oracle_exact_fraction": float(np.median(np.asarray([float(r["selector_oracle_exact_fraction"]) for r in rows]))),
        "median_oracle_address_switches": float(np.median(np.asarray([float(r["oracle_address_switches"]) for r in rows]))),
        "median_selector_switches": float(np.median(np.asarray([float(r["selector_switches"]) for r in rows]))),
        "median_inactive_damage_epochs": float(np.median(np.asarray([float(r["inactive_damage_epochs"]) for r in rows]))),
        "median_inactive_improve_epochs": float(np.median(np.asarray([float(r["inactive_improve_epochs"]) for r in rows]))),
        "median_acceptance_fraction": float(np.median(np.asarray([float(r["acceptance_fraction"]) for r in rows]))),
        "max_material_sum_relative_error": float(np.max(np.asarray([float(r["material_sum_relative_error"]) for r in rows]))),
    }


def run_all(out_dir: Path, seeds: int = 3, epochs: int = 45, slow_proposals: int = 36):
    out_dir.mkdir(parents=True, exist_ok=True)
    modes = ["coadaptive", "stale", "oracle_fast", "selector_only"]
    runs = {
        mode: [
            run_mode(mode, seed=s, epochs=epochs, slow_proposals=slow_proposals)
            for s in range(seeds)
        ]
        for mode in modes
    }
    summary = {mode: summarize(rs) for mode, rs in runs.items()}
    best = max(
        runs["coadaptive"],
        key=lambda x: float(x["result"]["final_selected"]["min_ratio"]),
    )
    write_svg(out_dir / "gate6_moving_target_topology.svg", best["grid"], best["g"])
    receipt = {
        "gate": "6B",
        "question": "When task-specific local writes alter one shared resonant material, do the best physical addresses move, and does an online scalar-probe selector earn an advantage over stale addresses?",
        "stress": "one task at a time is allowed to improve its selected address with local conservative material transfers; other tasks are unprotected",
        "address_space": "3 nearby source rows x 5 frequencies = 15 addresses",
        "controls": {
            "stale": "freeze each task at its blank-medium best address",
            "oracle_fast": "audit upper bound that rescans every address before structural learning",
            "selector_only": "learn addresses with frozen material",
        },
        "summary": summary,
        "runs": {mode: [x["result"] for x in rs] for mode, rs in runs.items()},
        "claim_boundary": "The task labels, receiver utilities, discrete address bank, and digital selector are engineered. Oracle scans are audit/control only. A positive result would establish a moving-address co-adaptation mechanism in this toy, not autonomous semantics or a biological learning law.",
    }
    (out_dir / "gate6_moving_target.json").write_text(json.dumps(receipt, indent=2), encoding="utf-8")
    return receipt


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="results")
    p.add_argument("--seeds", type=int, default=3)
    p.add_argument("--epochs", type=int, default=45)
    p.add_argument("--slow-proposals", type=int, default=36)
    args = p.parse_args()
    receipt = run_all(Path(args.out), seeds=args.seeds, epochs=args.epochs, slow_proposals=args.slow_proposals)
    print(json.dumps(receipt["summary"], indent=2))


if __name__ == "__main__":
    main()
